"""
Django settings for ridechain project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from corsheaders.defaults import default_headers

# Initialise environment variables
env = environ.Env()
env.escape_proxy = True
environ.Env.read_env()

APP_ENV = env('APP_ENV')
IS_PRODUCTION = APP_ENV == 'production'

if IS_PRODUCTION:
    PAYSTACK_SECRET_KEY = env('PAYSTACK_LIVE_KEY')
else:
    PAYSTACK_SECRET_KEY = env('PAYSTACK_TEST_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = APP_ENV != 'production'

ALLOWED_HOSTS = [
    '*', 'localhost',
    '127.0.0.1',
    'yaw959.pythonahywhere.com',
    'api.paystack.co',
    'app.arcaccra.com'
]

templates = os.path.join(BASE_DIR, 'templates')
static = os.path.join(BASE_DIR / 'static')
media = os.path.join(BASE_DIR / 'media')

AUTH_USER_MODEL = 'accounts.User'
# Application definition

INSTALLED_APPS = [
    'accounts',
    'homepage',
    'rides',
    'book_rate',
    'community',
    'apis',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'corsheaders',
    'django_countries',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ridechain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [templates],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ridechain.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': env('DB_HOST'),
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASS'),
            'PORT': env('DB_PORT'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'use_unicode': True,
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    # List of authentication classes used for API requests
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
}

# CORS (Cross-Origin Resource Sharing) configuration
CORS_ORIGIN_ALLOW_ALL = True  # Allow all origins (not recommended for production)
CORS_ORIGIN_WHITELIST = [
    "http://localhost:8000",  # Local development
    "http://127.0.0.1:8000",  # Local Django server
    "https://yaw959.pythonahywhere.com",  # Deployed frontend/backend
    "https://app.arcaccra.com",  # Production frontend
    "http://127.0.0.1:3000",
    "http://localhost:3000",# Local frontend (e.g., React)
    "https://api.paystack.co",  # Paystack API
    "http://localhost:5173", # Local development server for frontend
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost",  # Local development
    "http://127.0.0.1",  # Local Django server
    "https://yaw959.pythonahywhere.com",  # Deployed frontend/backend
    "https://app.arcaccra.com",  # Production frontend
    "http://127.0.0.1:3000",  # Local frontend (e.g., React)
    "https://api.paystack.co",  # Paystack API
    "http://localhost:5173",
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/static/'
STATICFILES_DIRS = (static, )
# Media files (User-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = media

# Email configuration
# Use the custom insecure email backend
if IS_PRODUCTION:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'ridechain.insecure_email.InsecureEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_USER')  # Your Google Workspace email address
EMAIL_HOST_PASSWORD = env('EMAIL_PASS') # The 16-character App Password you generated
EMAIL_TIMEOUT = 10  # seconds
# Default sender email address matches the authenticated host user for consistency
DEFAULT_FROM_EMAIL = 'RideChain <' + EMAIL_HOST_USER + '>'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
