# Generated by Django 5.2.1 on 2025-07-18 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ghana_post_gps', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='departure time')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='arrival time')),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.driver', verbose_name='driver')),
                ('drop_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_offs', to='rides.location', verbose_name='drop-off location')),
                ('passengers', models.ManyToManyField(blank=True, related_name='rides', to=settings.AUTH_USER_MODEL, verbose_name='passengers')),
                ('pick_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_ups', to='rides.location', verbose_name='pick-up location')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-created_at'],
            },
        ),
    ]
